### ISSUE TITLE
App Feedback from Alycia and George

### ISSUE THREAD

**Issue by alyciakb** [UBC-MDS/wine_viz_mkpv#17]
- Colour choices are pleasing and cohesive

- I was able to accidentally click on something and it made the map disappear
- The slider for prices makes goes from $0 - $10,000 and many wines are $200 or less, but it's very hard to get to that price range in the slider.
- An error occurs if you select a variables that lead to no results, but it doesn't explain to the user what the error is or how to fix it.
- Side panel can be more narrow
- Outliers squish the data in the bottom right plot

**Comment by mkeyim** [comment]
- Price ranges updated to show a price category instead of a slider filter to better handle outliers. 
- side panel width set to be mroe narrow
- error message added to show when "no wines are selected"
