### ISSUE TITLE
Feedback from Sylvia and Birinder

### ISSUE THREAD

**Issue by LeeYinYing** [UBC-MDS/wine_viz_mkpv#18]
- Add the link to the Read Me file 
- Choice of color is good, nice color scheme
- Error happens at some price ranges because there are no wine data
- Missing "$" for the price range
- Select/Deselect all is good feature, but is unresponsive 
- The scale for the scatter plot can be improved. The points are all clusters on the bottom seems like over-plotting
- Make selection panel skinnier so that you may have more room for the graphs

**Comment by mkeyim** [comment]
Added more information to README, fixed error message for price ranges, added in the USD$ for price range, selection has been updated, and the panel has been made thinner.
